// OTOMATİK ÜRETİLDİ — kaynak: Keyword Stats CSV (Google Keyword Planner).
// Düzenleme yerine üreticiyi güncelle. Marka hub sayfaları bu veriden üretilir.

export type Brand = {
  slug: string;
  name: string;
  searchVolume: number;
  keywordCount: number;
  keywords: string[];
};

export const brands: Brand[] = [
  {
    "slug": "opel",
    "name": "Opel",
    "searchVolume": 22600,
    "keywordCount": 155,
    "keywords": [
      "opel astra arıza lambaları ve anlamları",
      "opel gösterge paneli işaretleri",
      "opel arıza lambası",
      "opel astra arıza lambaları",
      "opel astra arıza ışıkları",
      "opel astra gösterge işaretleri",
      "opel astra gösterge paneli anlamları",
      "opel astra j motor arıza lambası söndürme",
      "opel astra motor arıza lambası",
      "opel astra motor arıza lambası söndürme",
      "opel combo arıza lambaları ve anlamları",
      "opel corsa anahtar işareti",
      "opel corsa motor arıza lambası",
      "araç ikaz lambaları opel",
      "arıza lambaları opel",
      "astra motor arıza lambası",
      "corsa motor arıza lambası",
      "insignia motor arıza lambası",
      "motor arıza lambası opel astra",
      "opel abs beyin tamiri",
      "opel ariza isaretleri",
      "opel ariza lambalari",
      "opel arıza göstergeleri",
      "opel arıza sembolleri"
    ]
  },
  {
    "slug": "fiat",
    "name": "Fiat",
    "searchVolume": 20700,
    "keywordCount": 126,
    "keywords": [
      "doblo arıza lambaları anlamları",
      "egea gösterge işaretleri",
      "egea ikaz lambaları anlamları",
      "egea motor arıza lambası",
      "egea motor arıza lambası sarı yanıyor",
      "fiat arıza lambaları",
      "fiat doblo 1.3 multijet motor arıza lambası söndürme",
      "fiat doblo arıza işaretleri",
      "fiat doblo arıza lambaları",
      "fiat doblo arıza lambaları anlamları",
      "fiat doblo gösterge paneli işaretleri",
      "fiat doblo ikaz lambaları",
      "fiat egea arıza lambaları anlamları",
      "fiat egea arıza ışıkları",
      "fiat egea gösterge işaretleri",
      "fiat egea ikaz lambaları",
      "fiat egea ikaz lambaları ve anlamları",
      "fiat egea marş basmıyor",
      "fiat egea marş basıyor ama çalışmıyor",
      "fiat fiorino arıza lambaları",
      "fiat fiorino gösterge paneli anlamları",
      "fiat fiorino marş basıyor ama çalışmıyor",
      "fiat fiorino motor arıza lambası söndürme",
      "fiat linea 1.3 multijet arıza göstergeleri"
    ]
  },
  {
    "slug": "ford",
    "name": "Ford",
    "searchVolume": 18950,
    "keywordCount": 145,
    "keywords": [
      "ford transit ikaz lambaları ve anlamları",
      "2012 ford transit ikaz lambaları ve anlamları",
      "ford arıza lambaları anlamları",
      "ford connect ikaz lambaları anlamları",
      "ford connect marş basıyor ama çalışmıyor",
      "ford courier ikaz lambaları",
      "ford fiesta arıza lambaları",
      "ford fiesta motor arıza lambası söndürme",
      "ford focus arıza lambaları",
      "ford focus gösterge paneli işaretleri",
      "ford ikaz lambaları",
      "ford motor arızası servise gidin",
      "ford transit gösterge işaretleri",
      "ford transit gösterge paneli ikaz ışıkları",
      "ford transit ikaz lambalari",
      "ford transit ikaz lambaları anlamı",
      "2004 ford focus arıza lambaları",
      "2007 ford focus arıza lambaları",
      "2011 ford focus motor arıza lambası",
      "2020 ford transit arıza lambaları",
      "2020 ford transit gösterge paneli anlamları",
      "2021 ford transit arıza lambaları",
      "araba arıza işaretleri ford",
      "connect gösterge paneli işaretleri"
    ]
  },
  {
    "slug": "renault",
    "name": "Renault",
    "searchVolume": 17750,
    "keywordCount": 94,
    "keywords": [
      "renault arıza ışıkları anlamları",
      "clio arıza lambaları",
      "megane 2 marş basmıyor",
      "renault arıza lambaları",
      "renault arıza ışıkları",
      "renault clio arıza lambaları",
      "renault clio ikaz lambaları anlamları",
      "renault ikaz lambaları anlamları",
      "renault master ikaz lambaları anlamları",
      "renault megane ikaz lambaları anlamları",
      "renault symbol ariza isaretleri",
      "renault symbol arıza lambaları",
      "renault symbol arıza ışıkları",
      "renault symbol arıza ışıkları anlamları",
      "renault symbol elektronik arıza ikaz lambası",
      "renault symbol gösterge paneli işaretleri",
      "renault symbol ikaz lambaları",
      "renault symbol ikaz lambaları anlamları",
      "symbol arıza lambası",
      "2011 fluence arıza lambaları",
      "2014 symbol arıza lambaları",
      "clio 2 beyin tamiri",
      "clio 3 marş basmıyor",
      "clio 4 marş basmıyor"
    ]
  },
  {
    "slug": "volkswagen",
    "name": "Volkswagen",
    "searchVolume": 16150,
    "keywordCount": 107,
    "keywords": [
      "volkswagen arıza lambaları ve anlamları",
      "jetta arıza lambaları",
      "jetta arıza ışıkları",
      "jetta ikaz lambaları",
      "passat arıza lambaları",
      "passat motor arıza lambası",
      "polo arıza lambaları",
      "polo gösterge paneli anlamları",
      "volkswagen arıza lambaları anlamları",
      "volkswagen caddy arıza lambaları",
      "volkswagen ikaz lambaları",
      "volkswagen ikaz lambaları ve anlamları",
      "volkswagen motor arıza lambası",
      "volkswagen polo arıza lambaları",
      "2007 passat arıza lambaları",
      "2010 passat arıza göstergeleri",
      "2012 polo arıza lambaları",
      "arıza lambaları volkswagen",
      "caddy arıza lambaları ve anlamları",
      "caddy beyin fiyatı",
      "caddy direksiyon arıza lambası",
      "caddy ikaz işaretleri",
      "caddy ikaz lambası anlamları",
      "caddy motor arıza lambası"
    ]
  },
  {
    "slug": "audi",
    "name": "Audi",
    "searchVolume": 7450,
    "keywordCount": 60,
    "keywords": [
      "audi a3 arıza lambaları",
      "audi a3 ikaz lambaları ve anlamları",
      "audi a4 arıza lambaları",
      "audi a4 ikaz lambaları ve anlamları",
      "audi a6 ikaz lambaları ve anlamları",
      "audi ariza isaretleri",
      "audi arıza lambaları",
      "audi arıza lambaları anlamları",
      "audi epc arızası",
      "audi ikaz lambaları",
      "2012 audi a3 arıza lambaları",
      "audi a3 arıza göstergeleri",
      "audi a3 arıza ışıkları",
      "audi a3 gösterge paneli anlamları",
      "audi a3 gösterge paneli işaretleri",
      "audi a3 ikaz lambaları",
      "audi a3 marş basmıyor",
      "audi a3 motor arıza lambası",
      "audi a3 sarı ikaz lambaları ve anlamları",
      "audi a3 servis ışığı söndürme",
      "audi a4 airbag ışığı yanıyor",
      "audi a4 ariza gostergeleri",
      "audi a4 arıza göstergeleri",
      "audi a4 arıza lambası söndürme"
    ]
  },
  {
    "slug": "citroen",
    "name": "Citroën",
    "searchVolume": 4100,
    "keywordCount": 37,
    "keywords": [
      "citroen arıza lambası",
      "citroen c elysee motor arıza lambası söndürme",
      "citroen c elysee motor arızası aracı tamir ettiriniz",
      "citroen ikaz lambaları anlamları",
      "citroën c4 gösterge paneli anlamları",
      "citroen arıza göstergeleri",
      "citroen arıza lambası söndürme",
      "citroen berlingo 1.9 ikaz lambaları anlamları",
      "citroen berlingo arıza göstergeleri",
      "citroen berlingo gösterge işaretleri",
      "citroen berlingo gösterge paneli işaretleri",
      "citroen berlingo gösterge paneli işaretleri anlamları",
      "citroen berlingo marş basmıyor",
      "citroen berlingo uyarı ışıkları",
      "citroen beyin tamiri",
      "citroen c elysee egzoz emisyon arızası",
      "citroen c3 arıza göstergeleri",
      "citroen c3 arıza ışıkları",
      "citroen c3 gösterge işaretleri anlamları",
      "citroen c3 gösterge paneli arızası",
      "citroen c3 gösterge paneli işaretleri",
      "citroen c3 ikaz lambaları anlamları",
      "citroen c3 marş basıyor araba çalışmıyor",
      "citroen c3 uyarı ışıkları"
    ]
  },
  {
    "slug": "peugeot",
    "name": "Peugeot",
    "searchVolume": 4050,
    "keywordCount": 36,
    "keywords": [
      "peugeot 301 arıza lambaları",
      "peugeot 301 motor arıza lambası söndürme",
      "peugeot arıza lambaları anlamları",
      "peugeot ikaz lambaları anlamları",
      "peugeot motor arıza lambası söndürme",
      "307 motor arıza lambası",
      "motor arızası aracı tamir ettiriniz peugeot",
      "partner motor arıza lambası",
      "pejo 301 servis ışığı söndürme",
      "pejo 307 motor arıza lambası",
      "peugeot 2008 ikaz lambaları",
      "peugeot 2008 start stop çalışmıyor",
      "peugeot 206 km göstergesi çalışmıyor",
      "peugeot 206 km sayacı çalışmıyor",
      "peugeot 206 marş basıyor ama çalışmıyor",
      "peugeot 206 motor arıza lambası",
      "peugeot 206 motor arıza lambası söndürme",
      "peugeot 207 marş basmıyor",
      "peugeot 301 bakım ışığı söndürme",
      "peugeot 301 motor arıza lambası",
      "peugeot 307 arıza lambaları anlamları",
      "peugeot 307 gösterge işaretleri ve anlamları",
      "peugeot 307 motor arıza lambası söndürme",
      "peugeot 308 motor arıza lambası söndürme"
    ]
  },
  {
    "slug": "toyota",
    "name": "Toyota",
    "searchVolume": 3800,
    "keywordCount": 40,
    "keywords": [
      "toyota arıza lambaları",
      "toyota corolla ariza isaretleri",
      "toyota corolla arıza lambaları",
      "toyota motor arıza lambası sarı yanıyor",
      "auris motor arıza lambası",
      "corolla marş basmıyor",
      "toyota ariza simgeleri",
      "toyota auris arıza lambaları",
      "toyota auris arıza lambaları anlamları",
      "toyota auris marş basmıyor",
      "toyota auris motor arıza lambası",
      "toyota auris motor arıza lambası söndürme",
      "toyota beyin tamiri",
      "toyota check engine uyarısı",
      "toyota corolla 1.4 d 4d motor arıza lambası",
      "toyota corolla airbag lambası yanıyor",
      "toyota corolla anahtar arıza lambası",
      "toyota corolla arıza göstergeleri",
      "toyota corolla arıza lambaları anlamları",
      "toyota corolla arıza lambası söndürme",
      "toyota corolla check engine arızası",
      "toyota corolla check engine silme",
      "toyota corolla gösterge paneli işaretleri",
      "toyota corolla hararet göstergesi arızası"
    ]
  },
  {
    "slug": "hyundai",
    "name": "Hyundai",
    "searchVolume": 3500,
    "keywordCount": 34,
    "keywords": [
      "hyundai accent arıza lambaları anlamları",
      "hyundai i20 arıza lambaları",
      "hyundai i20 marş basmıyor",
      "hyundai i20 motor arıza lambası söndürme",
      "hyundai accent arıza lambaları",
      "hyundai accent blue motor arıza lambası",
      "hyundai accent blue motor arıza lambası söndürme",
      "hyundai accent ekran gösterge paneli işaretleri",
      "hyundai accent era arıza lambaları",
      "hyundai accent era gösterge paneli anlamları",
      "hyundai arıza lambaları",
      "hyundai getz check lambası",
      "hyundai getz check ışığı yanıyor",
      "hyundai getz gösterge paneli işaretleri anlamları",
      "hyundai getz gösterge ışıkları anlamları",
      "hyundai getz ikaz lambaları",
      "hyundai getz motor arıza lambası",
      "hyundai getz motor arıza lambası söndürme",
      "hyundai i10 marş basmıyor",
      "hyundai i20 araba çalışmıyor",
      "hyundai i20 arıza lambası söndürme",
      "hyundai i20 gösterge paneli işaretleri anlamları",
      "hyundai i20 ikaz lambaları anlamları",
      "hyundai i20 motor arıza lambası"
    ]
  },
  {
    "slug": "mercedes",
    "name": "Mercedes",
    "searchVolume": 2350,
    "keywordCount": 20,
    "keywords": [
      "mercedes motor arıza lambası",
      "mercedes motor arıza lambası sarı yanıyor",
      "mercedes sprinter ikaz lambaları ve anlamları",
      "c180 motor arıza lambası",
      "mercedes a180 motor arıza lambası",
      "mercedes axor beyin fiyatları",
      "mercedes beyin tamiri",
      "mercedes c 200 d motor arıza ışığı söndürme",
      "mercedes c180 akü uyarısı",
      "mercedes c180 marş basmıyor",
      "mercedes c200 arıza işaretleri",
      "mercedes c200 motor arıza lambası",
      "mercedes cla motor arıza ışığı",
      "mercedes epc arızası",
      "mercedes kamyon arıza lambaları",
      "mercedes motor ışığı yanıyor",
      "mercedes sprinter beyin fiyatları",
      "mercedes sprinter motor arıza lambası yanıp sönüyor",
      "mercedes sprinter motor arıza lambası yanıyor",
      "sprinter motor lambası yanıp sönüyor"
    ]
  },
  {
    "slug": "skoda",
    "name": "Skoda",
    "searchVolume": 1900,
    "keywordCount": 20,
    "keywords": [
      "skoda arıza lambaları anlamları",
      "skoda octavia arıza lambaları anlamları",
      "2005 skoda fabia gösterge paneli anlamları",
      "epc arızası skoda",
      "octavia motor arıza lambası",
      "skoda arıza göstergeleri",
      "skoda fabia bakım lambası söndürme",
      "skoda fabia beyin fiyatı",
      "skoda fabia epc lambası yanıyor",
      "skoda fabia gösterge paneli anlamları",
      "skoda fabia motor arıza lambası",
      "skoda felicia marş basmıyor",
      "skoda gösterge paneli anlamları",
      "skoda ikaz lambaları anlamları",
      "skoda motor arıza lambası",
      "skoda octavia epc arızası",
      "skoda octavia motor arıza lambası",
      "skoda octavia motor arıza lambası söndürme",
      "skoda superb motor arıza lambası",
      "skoda uyarı lambaları"
    ]
  },
  {
    "slug": "bmw",
    "name": "BMW",
    "searchVolume": 1150,
    "keywordCount": 14,
    "keywords": [
      "bmw motor arıza lambası sarı yanıyor",
      "bmw airbag tamiri",
      "bmw airbag tamiri fiyat",
      "bmw arıza lamba işaretleri",
      "bmw beyin tamiri",
      "bmw e90 marş basmıyor",
      "bmw marş basıyor ama çalışmıyor",
      "bmw motor arıza ışığı",
      "bmw x3 arıza lambaları",
      "bmw x3 gösterge işaretleri",
      "bmw x3 ikaz lambaları",
      "bmw yağ lambası sarı yanıyor",
      "bmw şanzıman arıza işareti",
      "bmw şanzıman arıza lambası"
    ]
  }
];

export function getBrand(slug: string): Brand | undefined {
  return brands.find((b) => b.slug === slug);
}
